//
// Created by fok poon kai on 2018-04-03.
//

#ifndef COMP345P1_VICTORYCOINSOBSERVERDECORATOR_H
#define COMP345P1_VICTORYCOINSOBSERVERDECORATOR_H

#endif //COMP345P1_VICTORYCOINSOBSERVERDECORATOR_H
